name: Tests
on: [push, pull_request]
jobs:
  php:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions:
          - '7.4'
          - '8.0'
        include:
          - php-versions: '8.1'
            composer-flags: '--ignore-platform-reqs'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer update -n ${{ matrix.composer-flags }}
      - name: Run Tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      - name: Run mutation tests
        if: ${{ matrix.php-versions == 8.0 }}
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: |
          composer req infection/infection
          vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=100 --min-msi=100 -s -j4
      - name: Run phpstan
        if: ${{ matrix.php-versions == 8.0 }}
        run: |
          composer req phpstan/phpstan
          vendor/bin/phpstan analyse src -l 6
